const types = {
    // INBOX
    INITIAL_LOADING_INBOX: 'INITIAL_LOADING_INBOX',
    INBOX_UPDATE_BY_MESSAGE: 'INBOX_UPDATE_BY_MESSAGE',
    INBOX_UPDATE_COUNTER: 'INBOX_UPDATE_COUNTER',
    INBOX_UPDATE_COUNTER_BY_READ: 'INBOX_UPDATE_COUNTER_BY_READ',
    SELECTED_INBOX: 'SELECTED_INBOX',
    INBOX_NEW: 'INBOX_NEW',
    
    // USER
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',

    // MESSAGE
    MESSAGE_ADDED: 'MESSAGE_ADDED',
    LOAD_MESSAGES: 'LOAD_MESSAGES'
}

export default types
